# .github/workflows/release.yml
name: xz_releaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "xz*"
    # branches: [ "master" ]

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  dockerbuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: build
        run: docker build -t convertimage:latest ${{ github.workspace }}
      - name: saveSpace
        run: rm -rf /opt/hostedtoolcache
      - name: export
        run: docker save ConvertImage:latest | xz --threads=0 -9e --memlimit-compress=0 > ConvertImage.tar.xz
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ConvImage.tar.xz
          path: ${{ github.workspace }}/ConvertImage.tar.xz
          compression-level: 9 # max compression
